<?php
ini_set('display_errors', '0'); 
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: GET, POST, PATCH, PUT, DELETE, OPTIONS');
header('Access-Control-Allow-Headers: Origin, Content-Type, X-Auth-Token');
header('Content-Type: application/json');
header("Cache-Control: no-store, no-cache, must-revalidate, max-age=0");
header("Cache-Control: post-check=0, pre-check=0", false);
header("Pragma: no-cache");
include("connection.php");
include("functions_JSON.php");
$con=new connection;
$link=$con->CONNECT_DB();
if (mysqli_connect_errno()) echo "Failed to connect to db: ";
$id=$_GET['id'];
$uid=$_GET['uid'];
if($id==0)  REGISTER($con);
else if($id==1)  LOGIN($con);
else if($id==2)  FORGET($con);
else if($id==3){
    USER_INFO($con);
    MSGS($con);
    echo ',';
    PRDS($con);
    echo ',';
    LIKES($con);
    echo ',';
    CountsMsg($con,"select count(*) as cnt from send_msg where dest_id=$uid");
    echo ',';
    CountsLike($con,"select count(*) as likesCount from likes where user_id1=$uid");
}
else if($id==5)  PRDS($con);
else if($id==4)  MSGS($con);
else if($id==6)  LIKES($con);
else if($id==7)  SendMsg($con);
else if($id==8)  prdZoom($con);
else if($id==9)  Search_Service_List($con);
else if($id==10) CITYS($con);
else if($id==11) PROVS($con);
else if($id==12) MSGS_ZOOM($con);
else if($id==13) Search_Service_Type_List($con);
else if($id==14) Search_Service_Branch_List($con);
else if($id==15) MSGS_DEL($con);
else if($id==16) TakeLike($con);
else if($id==17) TakeLook($con);
else if($id==18) userList($con);
else if($id==19) userRate($con);
else if($id==20) userApply($con);
else if($id==21) userPrds($con);
else if($id==22) userEdit($con);
else if($id==23) USER_INFO($con);
else if($id==24) RecoveryPass($con);
else if($id==25) USER_INFO_FULL($con);
else if($id==26) userWishlist($con);
else if($id==27) userAddReWishlist($con);
else if($id==28) isInWishlist($con);
else if($id==29) increaseFieldOfTable($con);
else if($id==30) rateADos($con);
else if($id==31) visit($con);
else if($id==32) visitors($con);
else if($id==33) prdCount($con);
else if($id==34) deleteFromDashboard($con);
else if($id==35) deleteProfilePicture($con);
else if($id==36) simil($con);
else if($id==37) userApplyColor($con);
else if($id==38) searchShop($con);
else if($id==39) addtoBasket($con);
else if($id==40) userBasketlist($con);
else if($id==41) deleteFromBasket($con);
else if($id==42) userBasketlistCount($con);
else if($id==43) brands($con);
else if($id==44) sizeList($con);
else if($id==45) ColorList($con);
else if($id==46) userPaymenttlist($con);
else if($id==47) prdSizeToColor($con);
else if($id==48) prdgetCount($con);
else if($id==49) GetSizeExists($con);
else if($id==50) magList($con);
else if($id==51) magSearch($con);
else if($id==52) magazineZoom($con);
else if($id==53) magazineInsert($con);
else if($id==54) GroupList($con);
else if($id==55) magListLimit($con);
else if($id==56) magListGroup($con);
else if($id==57) searchNgDos($con);
else if($id==58) SubmitGoogle($con);
else if($id==59) Campaigns($con);
else if($id==60) PRDS_NEW($con);
else if($id==61) userWishlistCount($con);
else if($id==62) userEditNew($con);
else if($id==63) caroselPageOne($con);
else if($id==64) limitPrd($con);
else if($id==65) getSizes($con);
else if($id==66) intoDos($con);
else if($id==67) imgUpload($con);
else if($id==68) fetchCountry($con);
else if($id==69) getSex($con);
else if($id==70) getScentGroup($con);
else if($id==71) getPerfumer($con);
else if($id==72) coinMarket($con);
else if($id==73) insertcontent($con);
else if($id==74) allcontent($con);
else if($id==75) getScentType($con);
else if($id==76) getScent($con);
else if($id==77) getCountries($con);
$link->close();
?>